php:
  image: viljaste/php:5.5
  hostname: php
  ports:
    - "9000:9000"
  environment:
    - SERVER_NAME=localhost
    - DRUPAL_VERSION=8
    - POST_MAX_SIZE=512M
    - TIMEZONE=UTC
    - UPLOAD_MAX_FILESIZE=512M
    - SHORT_OPEN_TAG=On
    - MAX_EXECUTION_TIME=300
    - MAX_INPUT_VARS=4096
    - MEMORY_LIMIT=512M
    - DISPLAY_ERRORS=On
    - DISPLAY_STARTUP_ERRORS=On
    - ERROR_REPORTING=E_ALL
    - OPCACHE=On
    - XDEBUG=On
    - MEMCACHED=On
    - REDIS=On
    - BLACKFIRE=On
    - APCU=On
    - APD=On
